version: "3"

services:
  app:
    user: $UID:$GID
    build:
      #search for the dockerfile in the current directory
      context: .
      #expose port 8000 of container to port 8000 of local
    ports:
      - "8000:8000"
    volumes:
      #mount all the code in app directory in local to app directory of conatiner
      - ./app/:/app
    command: > #start the django server
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      #postgress specifications
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
